#!/bin/bash

echo "Before you stands a toad... ronin. With a straw hat lowered and a sword at his hip, he blocks your path"
echo "RoninToadin: Oho, a traveller? May I ask as to what you're doing here, it's quite cold and dangerous."
echo #blank line

n=2
while [ $n -le 5 ]; do
if [ $n -eq 1 ]; 
then
echo -e "\nGot something else to say?"
else 
((n=1))
fi
read -p "$(echo -e "[1] I'm delivering something for someone. You know an old 
man around here, probably wants a cookbook?
[2] What's a toad doing up on a mountain bridge?
[3] > Leave the ronin toad
[4] Wow cool sword
:")" input
case "$input" in
  1) echo -e "RoninToadin: Hmm, I see. I'll give you advice for your journey then. 
      If there's something that looks like it's too full of information, you can use
      a couple commands. Just type in "head [object]" or "tail [object]". It'll 
      narrow your view down to the top of bottom. Try using it on my shopping list."
      touch roninShoppingList
      ;;
  2) echo -e "RoninToadin: Why do you have such a mediocre haircut? I'm here to ensure people
  like you do not get lost."
     ;;
  3) echo "RoninToadin: Come back if you need something else."
     ((n=6))
     ;;
  4) echo "RoninToadin: I know right? Got it for like 20 bucks at a garage sale."
     ;; 
  *) echo "RoninRoadin: That's not what I was expecting..."
     ;;
esac
done


















































#Whoops! You should use the ". [Name]" command instead!
