#!/bin/bash

echo "Before you stands a toad... ronin. With a straw hat lowered and a sword at his hip, he blocks your path"
echo "RoninToadin: Oho, a traveller? May I ask as to what you're doing here, it's quite cold and dangerous."
echo " \n "

