#!/bin/bash
echo "Oh, well hello there."
echo "I see that you have some toadstools there."
echo "Would you like trade some for a CookBook page?"
echo "Or would you prefer to tell me a funny joke?"
echo "if you do ill let you go on to see youe 'Benefactor'."
echo "Be warned however, if the joke isnt funny I will use a fireball on you"
      cat <<EOF
        Please Select:
        1. trade 100 ToadStools
        2. tell the frog a joke
        3. leave him
EOF
read -p "Enter selection [1-3] > " selection
case $selection in
  1)
  if($TS < 100)
  then
  echo "sorry bud you dont seem to have enogh come back when you do"
  else
  export TS=1
  fi
  break
  ;;
  2)
  echo "You died"
  . ../../startup.sh
  fi
  ;;
  3)
  break
  ;;
  42)
  mv ../.hiddenfiles/Hut Swamp
  echo "ha Ha HA"
  sleep 10
  echo "HAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAAH"
  sleep 10
  echo "you may enter"
  ;;
  *)
  echo "Sorry player, this isn't a proper option!"
  ;;
  esac






























































There is something green garding a Hut. Try using the ". [name]" command.
