#!/bin/bash
art=$(</../../ToadStools/.hiddenfiles/bookart)
echo "$art"
echo "It's a wooden stand for a book, it's well-worn, but atop has an ornate book."
echo "the first page says to do $cd on blue files to travel there"















