#!/bin/bash
art=$(</../../ToadStools/.hiddenfiles/bookart)
echo "$art"

echo "The first page says to use $cd on blue files to travel to those locations."
echo "Example: \"cd Lake\"." 
echo " \*Disclaimer, not an actual teleportation spell, that'd ruin the travel mule industry"











































"It's a wooden stand for a book, it's well-worn, but atop has an ornate book."
