#!/bin/bash
echo "Ah, I see you have my cook book!"
echo "My apologies, I should introduce myself; my name is Benedict F. Acter. Professional wizard and cook."
echo "Since you've gone through all of this effort to get here, how about I cook the two of us a hearty meal?"




















































# Is this the benefactor? It's hard to tell, try using the ". OldMan" command. 
